### ISSUE TITLE
Satellite Index Page - User Story #19

### ISSUE THREAD

**Issue by jonathanmpope** [messages-from-the-stars/messages-from-the-stars-fe#24]
As a user, when I visit the satellite index page, I want to see all of the satellites I have attached a message to, and each should link to that satellite's show page, so that I can see all of the satellites I have messages attached to.

- [ ] API call to backend to retrieve all user satellites 
- [ ] Each satellite should be a link to it's show page

**Comment by tig-o** [comment]
Scrapped as reviewed on zoom with team on 9.17. Will move to another column
